# Generated by Django 5.0.1 on 2024-02-05 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0004_alter_mebel_options_mebel_parse_datetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mebel',
            options={'ordering': ['parse_datetime', 'price'], 'verbose_name': 'Мебель', 'verbose_name_plural': 'Мебель'},
        ),
    ]
